# Generated by Django 4.2 on 2023-09-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_publish_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
